# Exercício 1


In [17]:
import numpy as np

array_ones = np.ones(8, dtype=int)
print("Array de 1's:")
print(array_ones)


array_random = np.random.randint(0, 10, 8)
print("\nArray aleatório entre 0 e 9:")
print(array_random)

array_sum = array_ones + array_random
print("\nArray resultante da soma:")
print(array_sum)

total_sum = np.sum(array_sum)
print("\nSoma de todos os elementos do array resultante:", total_sum)

if total_sum >= 40:
    array_reshaped = array_sum.reshape(4, 2)
    print("\nComo a soma >= 40, o array foi remodelado para 4 linhas e 2 colunas:")
else:
    array_reshaped = array_sum.reshape(2, 4)
    print("\nComo a soma < 40, o array foi remodelado para 2 linhas e 4 colunas:")

print(array_reshaped)


Array de 1's:
[1 1 1 1 1 1 1 1]

Array aleatório entre 0 e 9:
[3 4 3 6 1 2 9 1]

Array resultante da soma:
[ 4  5  4  7  2  3 10  2]

Soma de todos os elementos do array resultante: 37

Como a soma < 40, o array foi remodelado para 2 linhas e 4 colunas:
[[ 4  5  4  7]
 [ 2  3 10  2]]


# Exercício 2


In [18]:
import numpy as np

array1 = np.arange(0, 52, 2)

array2 = np.arange(100, 49, -2)

array_concat = np.concatenate([array1, array2])

array_sorted = np.sort(array_concat)

print("Array de pares 0 a 51:", array1)
print("Array de pares 100 até 50 (decrescente):", array2)
print("Concatenado:", array_concat)
print("Ordenado:", array_sorted)


Array de pares 0 a 51: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
Array de pares 100 até 50 (decrescente): [100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50]
Concatenado: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50 100  98  96  94  92  90  88  86  84  82
  80  78  76  74  72  70  68  66  64  62  60  58  56  54  52  50]
Ordenado: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# Exercício 3


In [21]:
import numpy as np

board = np.zeros((2,2), dtype=int)
print(board)

# escolhe posição aleatória para colocar o 1
linha = np.random.randint(0,2)
coluna = np.random.randint(0,2)

board[linha, coluna] = 1

print(board)

# até 3 tentativas
for tentativa in range(3):
    l = int(input("Digite a linha (0 ou 1): "))
    c = int(input("Digite a coluna (0 ou 1): "))

    if board[l, c] == 1:
        print("Game Over! :( Try Again!")
        break
else:  # só executa se não der break
    print("Congratulations! You beat the game! :)")


[[0 0]
 [0 0]]
[[0 0]
 [1 0]]
Digite a linha (0 ou 1): 0
Digite a coluna (0 ou 1): 0
Digite a linha (0 ou 1): 0
Digite a coluna (0 ou 1): 0
Digite a linha (0 ou 1): 0
Digite a coluna (0 ou 1): 0
Congratulations! You beat the game! :)


# Exercício 4


In [24]:
import numpy as np

matriz = np.arange(12).reshape(3, 4)
print(matriz)

linhas, colunas = matriz.shape
print("\nLinhas:", linhas, " Colunas:", colunas)

total = linhas * colunas
print("Total de elementos:", total)


if total % 2 == 0:
    print("O vetor unidimensional teria um número PAR de elementos.")
else:
    print("O vetor unidimensional teria um número ÍMPAR de elementos.")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Linhas: 3  Colunas: 4
Total de elementos: 12
O vetor unidimensional teria um número PAR de elementos.


# Exercício 5

In [25]:
import numpy as np

matriz = np.random.randint(1, 51, (4, 4))
print(matriz)

# a) Médias de linhas e colunas
medias_linhas = np.mean(matriz, axis=1)
medias_colunas = np.mean(matriz, axis=0)
print("\nMédia de cada linha:", medias_linhas)
print("Média de cada coluna:", medias_colunas)

# b) Maior média das linhas e colunas
print("\nMaior média das linhas:", np.max(medias_linhas))
print("Maior média das colunas:", np.max(medias_colunas))

# c) Contagem de aparições
valores, contagens = np.unique(matriz, return_counts=True)
print("\nQuantidade de aparições de cada número:")
print(np.vstack((valores, contagens)).T)  # mostra em duas colunas (valor, contagem)

# Apenas números que aparecem 2 vezes
print("\nNúmeros que aparecem exatamente 2 vezes:")
print(valores[contagens == 2])


[[38  8  5 47]
 [33 21 10 10]
 [31  2 14 13]
 [13 50  7  5]]

Média de cada linha: [24.5  18.5  15.   18.75]
Média de cada coluna: [28.75 20.25  9.   18.75]

Maior média das linhas: 24.5
Maior média das colunas: 28.75

Quantidade de aparições de cada número:
[[ 2  1]
 [ 5  2]
 [ 7  1]
 [ 8  1]
 [10  2]
 [13  2]
 [14  1]
 [21  1]
 [31  1]
 [33  1]
 [38  1]
 [47  1]
 [50  1]]

Números que aparecem exatamente 2 vezes:
[ 5 10 13]
